// Security configuration
const SECURITY_CONFIG = {
  MAX_LOGIN_ATTEMPTS: 100,
  LOCKOUT_DURATION_MINUTES: 2,
  SESSION_DURATION_HOURS: 2,
  PASSWORD_EXPIRY_DAYS: 90,
  RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000, // 15 minutes
  RATE_LIMIT_MAX_REQUESTS: 100,
  SLOW_DOWN_WINDOW_MS: 15 * 60 * 1000, // 15 minutes
  SLOW_DOWN_DELAY_MS: 500,
  // Enhanced security settings
  MIN_PASSWORD_LENGTH: 12, // Increased from 8
  PASSWORD_COMPLEXITY_REQUIRED: true,
  SESSION_FINGERPRINTING: true,
  API_VERSION: 'v1',
  REQUEST_TIMEOUT_MS: 30000,
  MAX_REQUEST_SIZE: '10mb'
};

module.exports = SECURITY_CONFIG;