services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: webapp-postgres
    environment:
      POSTGRES_DB: webapp_db
      POSTGRES_USER: webapp_user
      POSTGRES_PASSWORD: webapp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webapp_user -d webapp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webapp-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://webapp_user:webapp_password@postgres:5432/webapp_db
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3001
      AUTO_MIGRATE: "true"
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    networks:
      - webapp-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webapp-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - webapp-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  webapp-network:
