services:
  # PostgreSQL Database Only
  postgres:
    image: postgres:15-alpine
    container_name: webapp-postgres-standalone
    environment:
      POSTGRES_DB: ${DB_NAME:-webapp_db}
      POSTGRES_USER: ${DB_USER:-webapp_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_standalone_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Optional: mount custom postgresql.conf
      # - ./postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - webapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-webapp_user} -d ${DB_NAME:-webapp_db}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    # Optional: resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    # Optional: logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_standalone_data:
    driver: local

networks:
  webapp-network:
    driver: bridge