services:
  # PostgreSQL Database
  postgres:
    image: postgres:17.6-alpine
    container_name: webapp-postgres
    environment:
      POSTGRES_DB: webapp_db
      POSTGRES_USER: webapp_user
      POSTGRES_PASSWORD: webapp_password
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webapp_user -d webapp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webapp-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://webapp_user:webapp_password@postgres:5432/webapp_db
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3001
      AUTO_MIGRATE: "true"
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    expose:
      - 3001
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    networks:
      - webapp-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webapp-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001
      CHOKIDAR_USEPOLLING: "true"
    expose:
      - 3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - webapp-network
    command: npm run dev

  # Telegram Bot
  telegram-bot:
    build:
      context: "./telegram bot"
      dockerfile: Dockerfile
    container_name: webapp-telegram-bot
    environment:
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: webapp_db
      DB_USER: webapp_user
      DB_PASSWORD: webapp_password
      
      # Telegram Bot Configuration
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      
      # Bot Configuration
      CHECK_INTERVAL_MINUTES: ${CHECK_INTERVAL_MINUTES:-1}
      REMINDER_MINUTES_BEFORE: ${REMINDER_MINUTES_BEFORE:-30}
      
      # Node.js Configuration
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - webapp-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  webapp-network:
